max allowed retries in reactive retry policy
Playtika/feign-reactive pull request #607
Opened 2023-06-22 07:48 UTC by mukeshj13

max allowed retries to avoid discard for unbounded integer set

2023-11-10 10:25 UTC, kptfh requested changes
Please remove all non related changes and rebase to the latest version

2023-11-10 20:52 UTC, mukeshj13 commented
@kptfh removed the unrelated changes

2023-11-13 09:08 UTC, kptfh approved these changes

2023-11-13 09:09 UTC, merged

2023-11-14 05:58 UTC, mukeshj13 commented
added commit for [feign-reactive/issues/590](https://github.com/PlaytikaOSS/feign-reactive/issues/590)